AddNewCostumeEmote("BigChamp", "png", "from google");
AddNewCostumeEmote("Eman", "png", "from google");
AddNewCostumeEmote("GE", "png", "from Goldenegg000");
AddNewCostumeEmote("CoolPepe", "png", "from google");
AddNewCostumeEmote("Countdown", "gif", "from google");
AddNewCostumeEmote("Pepedance", "gif", "from google");
AddNewCostumeEmote("Pepesaber", "gif", "from google");
AddNewCostumeEmote("PogChamp", "png", "from google");
AddNewCostumeEmote("Wha", "gif", "from google");
AddNewCostumeEmote("emerald", "png", "from Goldenegg000");
AddNewCostumeEmote("image", "png", "from google");
AddNewCostumeEmote("Bits1", "gif", "from google");
AddNewCostumeEmote("Bits100", "gif", "from google");
AddNewCostumeEmote("Bits1000", "gif", "from google");
AddNewCostumeEmote("Bits5000", "gif", "from google");
AddNewCostumeEmote("Bits10000", "gif", "from google");
AddNewCostumeEmote("Spoopydance", "gif", "from google");
AddNewCostumeEmote("Bfdab", "gif", "from google");
AddNewCostumeEmote("Bfdab", "png", "from google");
AddNewCostumeEmote("Cowdance", "gif", "from google");
AddNewCostumeEmote("Rickcubed", "gif", "from google");
AddNewCostumeEmote("Lol", "png", "from google");
AddNewCostumeEmote("Huhcat", "png", "from Omen");
AddNewCostumeEmote("Top1", "png", "from google");
AddNewCostumeEmote("Hot", "png", "MABY from chi_coded_dragon, JUST MABY");
AddNewCostumeEmote("Pepederp", "png", "from google");
console.log("finished loading emotes");
