AddNewCostumeEmote("BigChamp", "png");
AddNewCostumeEmote("Eman", "png");
AddNewCostumeEmote("GE", "png");
AddNewCostumeEmote("CoolPepe", "png");
AddNewCostumeEmote("Countdown", "gif");
AddNewCostumeEmote("Pepedance", "gif");
AddNewCostumeEmote("Pepesaber", "gif");
AddNewCostumeEmote("PogChamp", "png");
AddNewCostumeEmote("Wha", "gif");
AddNewCostumeEmote("emerald", "png");
AddNewCostumeEmote("image", "png");
AddNewCostumeEmote("Bits1", "gif");
AddNewCostumeEmote("Bits100", "gif");
AddNewCostumeEmote("Bits1000", "gif");
AddNewCostumeEmote("Bits5000", "gif");
AddNewCostumeEmote("Bits10000", "gif");
AddNewCostumeEmote("Spoopydance", "gif");
AddNewCostumeEmote("Bfdab", "gif");
AddNewCostumeEmote("Bfdab", "png");
AddNewCostumeEmote("Cowdance", "gif");
AddNewCostumeEmote("Rickcubed", "gif");
AddNewCostumeEmote("Lol", "png");
AddNewCostumeEmote("Huhcat", "png");
AddNewCostumeEmote("Top1", "png");
console.log("finished loading emotes");

