// AddNewCostumeEmote("BigChamp", "png", "from google");
// AddNewCostumeEmote("Eman", "png", "from google");
// AddNewCostumeEmote("GE", "png", "from Goldenegg000");
// AddNewCostumeEmote("GEM", "gif", "from Goldenegg000");
// AddNewCostumeEmote("CoolPepe", "png", "from google");
// AddNewCostumeEmote("Countdown", "gif", "from google");
// AddNewCostumeEmote("Pepedance", "gif", "from google");
// AddNewCostumeEmote("Pepesaber", "gif", "from google");
// AddNewCostumeEmote("PogChamp", "png", "from google");
// AddNewCostumeEmote("Wha", "gif", "from google");
// AddNewCostumeEmote("emerald", "png", "from Goldenegg000");
// AddNewCostumeEmote("image", "png", "from google");
// AddNewCostumeEmote("Bits1", "gif", "from google");
// AddNewCostumeEmote("Bits100", "gif", "from google");
// AddNewCostumeEmote("Bits1000", "gif", "from google");
// AddNewCostumeEmote("Bits5000", "gif", "from google");
// AddNewCostumeEmote("Bits10000", "gif", "from google");
// AddNewCostumeEmote("Spoopydance", "gif", "from google");
// AddNewCostumeEmote("Bfdab", "gif", "from google");
// AddNewCostumeEmote("Bfdab", "png", "from google");
// AddNewCostumeEmote("Cowdance", "gif", "from google");
// AddNewCostumeEmote("Rickcubed", "gif", "from google");
// AddNewCostumeEmote("Lol", "png", "from google");
// AddNewCostumeEmote("Huhcat", "png", "from Omen");
// AddNewCostumeEmote("Top1", "png", "from google");
// AddNewCostumeEmote("Hot", "png", "MABY from chi_coded_dragon, JUST MABY");
// AddNewCostumeEmote("Pepederp", "png", "from google");
// AddNewCostumeEmote("Oldsmile", "png", "from google");
// AddNewCostumeEmote("idc", "gif", "from google");
// AddNewCostumeEmote("ThumbSmile", "png", "from Omen");
// AddNewCostumeEmote("Sheriffsmile", "png", "from Omen");
// AddNewCostumeEmote("Noice", "gif", "from google");
// AddNewCostumeEmote("Mattspam", "gif", "from google");
// AddNewCostumeEmote("Johncenasus", "gif", "from google");
// AddNewCostumeEmote("Gift", "png", "from google");
// AddNewCostumeEmote("rockeyebrow", "png", "from google");
// AddNewCostumeEmote("darock", "png", "from google");
// AddNewCostumeEmote("smolbrain", "png", "from google");
// AddNewCostumeEmote("richkappa", "png", "from google");
// AddNewCostumeEmote("kappalife", "png", "from google");
// AddNewCostumeEmote("Wesmart", "png", "from geckobooi");
// AddNewCostumeEmote("Stonks", "png", "from geckobooi");
// AddNewCostumeEmote("Omegalul", "png", "from geckobooi");
// AddNewCostumeEmote("Kekw", "png", "from geckobooi");
// AddNewCostumeEmote("Doggo", "png", "from geckobooi");
// AddNewCostumeEmote("5head", "png", "from geckobooi");
// AddNewCostumeEmote("Geckobot", "png", "from geckobooi");
$.ajax({url: "https://api.github.com/repos/Goldenegg000/TwitchEmote/git/trees/main?recursive=1", success: (result) => {
    result.tree.forEach(item => {
        AddNewCostumeEmote(item.path.split(".")[0], item.path.split(".")[1], "pretty pog");
//         console.log(item.path);
    });
}});
console.log("finished loading emotes");
